### ISSUE TITLE
old style 0 and shavian 𐑴 look too similar

### ISSUE THREAD

**Issue by trosel** [Shavian-info/interalia#3]
when using old style numerals, the 0 and shavian 𐑴 look too similar. Maybe add a line through the 0 or something?

**Comment by trosel** [comment]
idea taken from here, by the way: https://brailleinstitute.org/freefont

Maybe it is beyond the goal, but something to be aware of

**Comment by Shavian-info** [comment]
You can turn on slashed zeros (including for old style figures) using the built in OpenType features.
